name: Perl Critic
on: [push]
jobs:
  perl-critic:
    name: Perl Critic Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Perl Critic checks
        uses: Difegue/action-perlcritic@2.0.0
        with:
          args: --brutal ./*.pl
